-- begin APOLLO_CONTACTS_TABLE
alter table APOLLO_CONTACTS_TABLE add constraint FK_APOLLO_CONTACTS_TABLE_ON_PROSPECTS foreign key (PROSPECTS_ID) references APOLLO_PROSPECTS(ID)^
create index IDX_APOLLO_CONTACTS_TABLE_ON_PROSPECTS on APOLLO_CONTACTS_TABLE (PROSPECTS_ID)^
-- end APOLLO_CONTACTS_TABLE
